### ISSUE TITLE
NuGet package is unavailable

### ISSUE THREAD

**Issue by liamgold** [Kentico/xperience-by-kentico-ecommerce-common#7]
**Describe the bug**

I have tried installing the [Shopify Integration](https://github.com/Kentico/xperience-by-kentico-shopify) and [Kentico Xperience 13 bridge](https://github.com/Kentico/xperience-by-kentico-k13ecommerce) through NuGet rather than a direct project reference, and you get an error message stating `Kentico.Xperience.Ecommerce.Common` cannot be found.

Can you please ensure that the NuGet package is published?

**To Reproduce**
1. Run `dotnet add package Kentico.Xperience.Shopify` or `dotnet add package Kentico.Xperience.K13Ecommerce`
2. See error:

```
error: NU1101: Unable to find package Kentico.Xperience.Ecommerce.Common. No packages exist with this id in source(s): nuget.org, NugetLocal. 
```

**Expected behavior**
Should be able to install the integrations through NuGet.

**Comment by martinkyjac** [comment]
Hi Liam,
We’re currently addressing the issue and are grateful for you highlighting it. We’ll keep you posted on our progress.

**Comment by michalJakubis** [comment]
Hi Liam, the Kentico.Xperience.Ecommerce.Common nuget has been released. The installation of Shopify and KX13Ecommerce package should work from now.
